[build]
  publish = "dist"
  command = "npx expo export --platform web"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-eval' 'unsafe-inline' https: data: blob:"
