[build]
  publish = "dist"
  command = "npx expo export --platform web && cp public/_headers dist/_headers"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-eval' 'unsafe-inline' blob: https:; default-src 'self' 'unsafe-inline' https: data: blob:; worker-src blob: 'self';"
    X-Frame-Options = "SAMEORIGIN"
